version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:7.0
    container_name: mcp-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mcp_vertx
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - mcp-network

  # MCP Vertx Application
  mcp-vertx-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-vertx-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/mcp_vertx?authSource=admin
      - JAVA_OPTS=-Xmx2g -Xms512m
    volumes:
      # Mount credentials directory for Gmail authentication
      - ./tokens:/app/tokens:ro
      # Mount resources directory for PDF files
      - ./src/resources:/app/resources:ro
    depends_on:
      - mongodb
    networks:
      - mcp-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/mcp/sse"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mongodb_data:
    driver: local

networks:
  mcp-network:
    driver: bridge 